"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Card } from "../../../../../components/common/Card";
import { InvoicePreview } from "../../../../../components/invoice/InvoicePreview";
import { updateAdminInvoice } from "../../../../../lib/admin-api";
import { loadInvoiceByNo } from "../../../../../lib/invoice-storage";
import { generatePdfBlob } from "../../../../../lib/pdf-document";
import type { InvoiceDetails } from "../../../../../types/invoice";

export default function AdminInvoiceEditPage() {
  const params = useParams<{ invoiceNo: string }>();
  const router = useRouter();
  const [data, setData] = useState<InvoiceDetails | null>(null);
  const [error, setError] = useState(""); const [success,setSuccess]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{loadInvoiceByNo(params.invoiceNo).then(setData).catch(()=>setError("Unable to load invoice."));},[params.invoiceNo]);
  if(!data)return <main className="admin-page"><Card className="admin-card"><h1>Edit Invoice</h1><p>{error||"Loading..."}</p></Card></main>;
  const patch=(value:Partial<InvoiceDetails>)=>setData(current=>current?{...current,...value}:current);
  const customer=data.quotation.customer;
  const updateCustomer=(key:keyof typeof customer,value:string)=>patch({quotation:{...data.quotation,customer:{...customer,[key]:value}}});
  async function save(){const currentData=data;if(!currentData)return;if(!window.confirm("Save these invoice changes and replace the current invoice PDF?"))return;setSaving(true);setError("");setSuccess("");try{const pdf=await generatePdfBlob("adminInvoiceEditPreview",{filename:`Hour-Coffee-Invoice-${currentData.invoiceNo}.pdf`});const updated=await updateAdminInvoice(params.invoiceNo,currentData,pdf);setData(updated);setSuccess("Invoice updated and PDF replaced successfully.");if(updated.invoiceNo!==params.invoiceNo)router.replace(`/admin/invoices/${updated.invoiceNo}/edit`);}catch(saveError){setError(saveError instanceof Error?saveError.message:"Unable to update invoice.");}finally{setSaving(false);}}
  return <main className="admin-page"><Card className="admin-card admin-edit-card"><div className="admin-page-header"><div><p className="admin-eyebrow">Invoice</p><h1>Edit {params.invoiceNo}</h1><p>The original quotation and payment receipt will not be changed. Calculated line items and totals are regenerated by the backend.</p></div><Link className="admin-link-button" href={`/admin/invoices/${params.invoiceNo}`}>Cancel</Link></div>
    {error?<p className="error">{error}</p>:null}{success?<div className="ok-summary">{success}</div>:null}
    <div className="admin-form-grid"><section><h2>Reference & Status</h2><label className="admin-field"><span>Invoice number</span><input value={data.invoiceNo} onChange={event=>patch({invoiceNo:event.target.value.toUpperCase()})} /></label><label className="admin-field"><span>Invoice-specific reference</span><input value={data.invoiceReference??""} onChange={event=>patch({invoiceReference:event.target.value})} /></label><label className="admin-field"><span>Invoice status</span><select value={data.invoiceStatus??"SUBMITTED"} onChange={event=>patch({invoiceStatus:event.target.value as InvoiceDetails["invoiceStatus"]})}>{["DRAFT","SUBMITTED","PENDING_PAYMENT_REVIEW","PAID","CONFIRMED","CANCELLED"].map(value=><option key={value}>{value}</option>)}</select></label><label className="admin-field"><span>Invoice discount percent</span><input type="number" min="0" max="100" step="0.01" value={data.quotation.discountPercent} onChange={event=>patch({quotation:{...data.quotation,discountPercent:Number(event.target.value)}})} /></label></section>
      <section><h2>Customer & Billing</h2>{([['name','Name'],['phone','Phone'],['email','Email'],['companyName','Company'],['companyRegNo','Company registration'],['billingAddress','Billing address']] as const).map(([key,label])=><label className="admin-field" key={key}><span>{label}</span><input value={customer[key]} onChange={event=>updateCustomer(key,event.target.value)} /></label>)}</section>
      <section><h2>Event Details</h2><label className="admin-field"><span>Event address</span><textarea rows={3} value={data.eventAddress} onChange={event=>patch({eventAddress:event.target.value})} /></label><label className="admin-field"><span>Dress code</span><input value={data.dressCode} onChange={event=>patch({dressCode:event.target.value})} /></label><label className="admin-field"><span>Custom dress code</span><input value={data.customDressCode} onChange={event=>patch({customDressCode:event.target.value})} /></label><label className="admin-field"><span>Environment</span><input value={data.environment} onChange={event=>patch({environment:event.target.value})} /></label><label className="admin-field"><span>Environment notes</span><textarea rows={3} value={data.environmentNotes} onChange={event=>patch({environmentNotes:event.target.value})} /></label></section>
      <section><h2>Internal Note</h2><label className="admin-field"><span>New note</span><textarea rows={5} value={data.internalNote??""} onChange={event=>patch({internalNote:event.target.value})} /></label><p className="admin-muted">Saving adds this note to the audit trail. Existing notes remain intact.</p><p className="admin-muted">Payment receipt: {data.receiptName||"Existing receipt preserved"}</p></section></div>
    <div className="print-document" aria-hidden="true"><InvoicePreview invoiceNo={data.invoiceNo} quotation={data.quotation} invoice={data} documentId="adminInvoiceEditPreview" showDownloadButton={false} /></div>
    <div className="admin-edit-actions"><button className="hc-button hc-button-primary" type="button" disabled={saving} onClick={save}>{saving?"Saving...":"Save Changes"}</button><Link className="hc-button hc-button-secondary" href={`/admin/invoices/${params.invoiceNo}`}>Cancel</Link></div>
  </Card></main>;
}
